### ISSUE TITLE
Tuned Model

### ISSUE THREAD

**Issue by davidec1976** [mscraftsman/generative-ai#51]
Hi, I'm trying to use "Mscc.Generative AI" library with APIkey work well, but win OAuth2 doesn't work.
I always get the exception on the CreateTunedModel call.

---

System.Net.Http.HttpRequestException
  HResult=0x80131500
  Message=Request failed
Request failed with Status Code: Unauthorized
{
  "error": {
    "code": 401,
    "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": "UNAUTHENTICATED"
  }
}

  Source=Mscc.GenerativeAI
  StackTrace:
   at Mscc.GenerativeAI.GenerativeAIExtensions.<EnsureSuccessAsync>d__17.MoveNext()
   at Mscc.GenerativeAI.GenerativeModel.<CreateTunedModel>d__46.MoveNext()
   at Program.<<Main>$>d__0.MoveNext() in C:\Users\david\Desktop\Progetti\ResponderIA\ResponderIA\Program.cs:line 32

---

This is my code:
using System.Reflection;
using Mscc.GenerativeAI;
using System.Collections.Generic;

// I tried different codes:
// gcloud auth application-default print-access-token
// client secret code
var googleAI = new GoogleAI(apiKey: null,"<client secret>");

var model = googleAI.GenerativeModel(model: Model.Gemini10Pro001);
model.ProjectId = "gen-lang-client-0860587592";

var parameters = new HyperParameters() { BatchSize = 2, LearningRate = 0.001f, EpochCount = 3 };
var dataset = new List<TuningExample>
{
	new() { TextInput = "What's magi number?", Output = "200" },
};
var request = new CreateTunedModelRequest(
    Model.Gemini10Pro001,
	"My Test Model",
	dataset,
	parameters);

var response = await model.CreateTunedModel(request);

---

Regards Davide

**Comment by jochenkirstaetter** [comment]
Hi @davidec1976 

Thanks for the response and sample code to understand the issue better.
Referring to the README, you need to have `gcloud` CLI command line tool installed on the system running your C# code. Then one needs to enable and use OAuth for the Google AI as described here - https://ai.google.dev/gemini-api/docs/oauth - first. This provides the necessary scopes for the library to access the resources to tune a model.

After you set up OAuth in your project you can proceed using the `AccessToken` instead of the `ApiKey`. The initialization is described here: https://github.com/mscraftsman/generative-ai?tab=readme-ov-file#choose-an-api-and-authentication-mode

Google AI with OAuth. Use `gcloud auth application-default print-access-token` to get the access token.
```
using Mscc.GenerativeAI;
// Google AI with OAuth. Use `gcloud auth application-default print-access-token` to get the access token.
var googleAi = new GoogleAI(accessToken: "<your value>");
var model = googleAi.GenerativeModel(model: Model.Gemini10Pro001);
...
```

Your code `var googleAI = new GoogleAI(apiKey: null,"");` does not provide the access token and therefore your call is unauthorized and returned as an HTTP 401.

Also, see the [Troubleshooting](https://github.com/mscraftsman/generative-ai?tab=readme-ov-file#troubleshooting-) section at the end of the README file.

In case that you are getting an HTTP 403 due to missing Authorization you need to extend the scopes of your OAuth access token to include "https://www.googleapis.com/auth/generative-language.tuning" and enable it in the consent dialog when you log in. Refer to [Set up application default credentials](https://ai.google.dev/gemini-api/docs/oauth#set-application-default) to specify the scopes.

![image](https://github.com/user-attachments/assets/7a554616-4447-4e1c-94b0-1d1a791a25f1)

There are also tests here  in the repository regarding the creation and handling of tuned models.
See here to inspect the test [Create_Tuned_Model](https://github.com/mscraftsman/generative-ai/blob/c0d8d9c1310aca0496752260fea658a5bb409d8f/tests/Mscc.GenerativeAI/GoogleAi_GeminiPro_Should.cs#L1480).

I hope this helps.

Cheers, JoKi
